name: LibreWolf
flatpak: io.gitlab.librewolf-community
system_bin:
can_isolate: true
desktop_file_name_prefix: io.gitlab.librewolf-community.librewolf-community
base: firefox
issues:
  en:
    - Unable to remove ui when not isolated
  nl:
    - UI kan niet worden verwijderd zonder isolatie
  es:
    - No se puede eliminar la interfaz de usuario cuando no está aislado
  it:
    - Impossibile rimuovere l'interfaccia utente se non isolata
  de:
    - Ohne Isolation lassen sich Browser-Bedienelemente nicht entfernen
